<a href="https://colab.research.google.com/github/Satyam6024/Disease-Prediction-by-Symtopms/blob/master/disease_identifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Mounting google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Loading the datasets
import pandas as pd
import numpy as np

train_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Disease identifier/Training.csv')
test_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Disease identifier/Training.csv')
train_df.head()

itching  skin_rash  ...         prognosis  Unnamed: 133
0        1          1  ...  Fungal infection           NaN
1        0          1  ...  Fungal infection           NaN
2        1          0  ...  Fungal infection           NaN
3        1          1  ...  Fungal infection           NaN
4        1          1  ...  Fungal infection           NaN

[5 rows x 134 columns]

In [ ]:
train_df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis',
       'Unnamed: 133'],
      dtype='object', length=134)

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 134 entries, itching to Unnamed: 133
dtypes: float64(1), int64(132), object(1)
memory usage: 5.0+ MB


In [ ]:
# dropping the useless column
train_df.drop(['Unnamed: 133'], axis = 1, inplace=True)


In [ ]:
train_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [ ]:
test_df.drop(['Unnamed: 133'], axis = 1, inplace=True)


In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [ ]:
# counting the value of prognosis 
train_df['prognosis'].value_counts()


Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
Allergy      

In [ ]:
train_df.isna().sum()


itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [ ]:
train_df.nunique()


itching                  2
skin_rash                2
nodal_skin_eruptions     2
continuous_sneezing      2
shivering                2
                        ..
inflammatory_nails       2
blister                  2
red_sore_around_nose     2
yellow_crust_ooze        2
prognosis               41
Length: 133, dtype: int64

In [ ]:
X_train= train_df.drop('prognosis', axis=1)
X_test= test_df.drop('prognosis', axis=1)

Y_train= np.array(train_df['prognosis'])
Y_test= np.array(test_df['prognosis'])

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [ ]:
test_df.head()

itching  skin_rash  ...  yellow_crust_ooze         prognosis
0        1          1  ...                  0  Fungal infection
1        0          1  ...                  0  Fungal infection
2        1          0  ...                  0  Fungal infection
3        1          1  ...                  0  Fungal infection
4        1          1  ...                  0  Fungal infection

[5 rows x 133 columns]

In [ ]:
Y_train_encode= pd.get_dummies(Y_train)
Y_test_encode= pd.get_dummies(Y_test)

In [ ]:
for i in range(len(Y_test)):
  sympt= []
  for a,b in X_test.iloc[i].to_dict().items():
    if ( b == 1):
      sympt.append(a)
  print(Y_test[i]+ ":" + str(sympt))
  print()

Streaming output truncated to the last 5000 lines.
Acne:['skin_rash', 'pus_filled_pimples', 'blackheads', 'scurring']

Acne:['skin_rash', 'pus_filled_pimples', 'blackheads', 'scurring']

Acne:['pus_filled_pimples', 'blackheads', 'scurring']

Acne:['skin_rash', 'blackheads', 'scurring']

Acne:['skin_rash', 'pus_filled_pimples', 'scurring']

Acne:['skin_rash', 'pus_filled_pimples', 'blackheads']

Acne:['skin_rash', 'pus_filled_pimples', 'blackheads', 'scurring']

Acne:['skin_rash', 'pus_filled_pimples', 'blackheads']

Acne:['skin_rash', 'pus_filled_pimples', 'scurring']

Acne:['skin_rash', 'blackheads', 'scurring']

Urinary tract infection:['burning_micturition', 'bladder_discomfort', 'foul_smell_of urine', 'continuous_feel_of_urine']

Urinary tract infection:['burning_micturition', 'bladder_discomfort', 'foul_smell_of urine', 'continuous_feel_of_urine']

Urinary tract infection:['bladder_discomfort', 'foul_smell_of urine', 'continuous_feel_of_urine']

Urinary tract infection:['burning_m

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import math


In [ ]:
# using DT based on information gain
classifierDT = DecisionTreeClassifier(splitter='best', criterion='entropy', min_samples_leaf=2)
classifierDT.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2)

In [ ]:
# using RF classifier
classifierRF = RandomForestClassifier(criterion='entropy', min_samples_leaf=2)
classifierRF.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', min_samples_leaf=2)

In [ ]:
y_predDT = classifierDT.predict(X_test)
y_predRF = classifierRF.predict(X_test)

In [ ]:
# for RF model
# using confusion matrix
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score


print(confusion_matrix(Y_test, y_predRF))
print(classification_report(Y_test, y_predRF))

# using accuracy performance metric
print("Train Accuracy: ", accuracy_score(Y_train, classifierRF.predict(X_train)))
print("Test Accuracy: ", accuracy_score(Y_test, y_predRF))

[[120   0   0 ...   0   0   0]
 [  0 120   0 ...   0   0   0]
 [  0   0 120 ...   0   0   0]
 ...
 [  0   0   0 ... 120   0   0]
 [  0   0   0 ...   0 120   0]
 [  0   0   0 ...   0   0 120]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00       120
                                   AIDS       1.00      1.00      1.00       120
                                   Acne       1.00      1.00      1.00       120
                    Alcoholic hepatitis       1.00      1.00      1.00       120
                                Allergy       1.00      1.00      1.00       120
                              Arthritis       1.00      1.00      1.00       120
                       Bronchial Asthma       1.00      1.00      1.00       120
                   Cervical spondylosis       1.00      1.00      1.00       120
                            Chicken pox       1.00      1.00      1.00       1

In [ ]:
# for DT model
# using confusion matrix
print(confusion_matrix(Y_test, y_predDT))
print(classification_report(Y_test, y_predDT))

# using accuracy performance metric
print("Train Accuracy: ", accuracy_score(Y_train, classifierDT.predict(X_train)))
print("Test Accuracy: ", accuracy_score(Y_test, y_predDT))

[[120   0   0 ...   0   0   0]
 [  0 120   0 ...   0   0   0]
 [  0   0 120 ...   0   0   0]
 ...
 [  0   0   0 ... 120   0   0]
 [  0   0   0 ...   0 120   0]
 [  0   0   0 ...   0   0 120]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00       120
                                   AIDS       1.00      1.00      1.00       120
                                   Acne       1.00      1.00      1.00       120
                    Alcoholic hepatitis       1.00      1.00      1.00       120
                                Allergy       1.00      1.00      1.00       120
                              Arthritis       1.00      1.00      1.00       120
                       Bronchial Asthma       1.00      1.00      1.00       120
                   Cervical spondylosis       1.00      1.00      1.00       120
                            Chicken pox       1.00      1.00      1.00       1

In [ ]:
# identify the important features in DT
imp = classifierDT.feature_importances_
imp

array([0.02984509, 0.05380291, 0.00228577, 0.        , 0.00873855,
       0.01387133, 0.00420773, 0.00563969, 0.        , 0.00300042,
       0.        , 0.0998201 , 0.00301006, 0.00125416, 0.15787755,
       0.        , 0.        , 0.        , 0.        , 0.00126828,
       0.        , 0.        , 0.        , 0.        , 0.00671323,
       0.05874982, 0.        , 0.00337988, 0.00252244, 0.0009105 ,
       0.        , 0.03259118, 0.00942588, 0.00259035, 0.04582923,
       0.06947116, 0.        , 0.        , 0.        , 0.03152842,
       0.01150862, 0.        , 0.        , 0.02630033, 0.00045525,
       0.        , 0.00062708, 0.        , 0.02770816, 0.        ,
       0.01120421, 0.0009105 , 0.        , 0.0081945 , 0.        ,
       0.        , 0.03980449, 0.        , 0.        , 0.0121364 ,
       0.        , 0.        , 0.00098983, 0.02705534, 0.00045525,
       0.0009105 , 0.        , 0.00164329, 0.        , 0.        ,
       0.        , 0.00841768, 0.        , 0.        , 0.     

In [ ]:
columns = list(train_df.columns)

In [ ]:
# combine list of symptoms and their feature importance into a 2D array
columns = columns[:132]
column_names = ['symptom', 'importance']
df3 = np.vstack((columns, imp)).T
df3 = pd.DataFrame(df3, columns = column_names)
df3

symptom             importance
0                 itching   0.029845091087645135
1               skin_rash    0.05380291041928537
2    nodal_skin_eruptions  0.0022857736489585367
3     continuous_sneezing                    0.0
4               shivering    0.00873854795743233
..                    ...                    ...
127  small_dents_in_nails  0.0006270809694766358
128    inflammatory_nails                    0.0
129               blister   0.001303821527248525
130  red_sore_around_nose                    0.0
131     yellow_crust_ooze   0.010749695051767143

[132 rows x 2 columns]

In [ ]:
coefficients = classifierDT.feature_importances_

# set a minimum threshold for feature importance
importance_threshold = np.quantile(coefficients, q = 0.75)
import plotly.express as px

# barplot of feature importance
fig = px.bar(x = coefficients, y = columns, orientation = 'h', color = coefficients, 
             color_continuous_scale = [(0, '#b7d2e8'), (1, '#295981')], labels = {'x': "Importance Value", 'y': "Feature"}, 
             title = "Feature Importance For Decision Tree Model")

# cut off value as the minimum threshold for feature importance
fig.add_vline(x = importance_threshold, line_color = 'red', line_width = 0.8)
fig.add_vrect(x0 = importance_threshold, x1 = 0, line_width = 0, fillcolor = 'red', opacity = 0.2)
fig.show()


In [ ]:
import numpy
# identify features with feature importance values below the minimum threshold
low_importance_features = numpy.array(df3.symptom[np.abs(coefficients) <= importance_threshold])
columns = list(low_importance_features)
columns

['nodal_skin_eruptions',
 'continuous_sneezing',
 'joint_pain',
 'stomach_pain',
 'acidity',
 'ulcers_on_tongue',
 'muscle_wasting',
 'burning_micturition',
 'spotting_ urination',
 'weight_gain',
 'anxiety',
 'cold_hands_and_feets',
 'mood_swings',
 'weight_loss',
 'restlessness',
 'lethargy',
 'patches_in_throat',
 'irregular_sugar_level',
 'sunken_eyes',
 'breathlessness',
 'sweating',
 'dehydration',
 'indigestion',
 'dark_urine',
 'pain_behind_the_eyes',
 'back_pain',
 'constipation',
 'mild_fever',
 'yellow_urine',
 'acute_liver_failure',
 'fluid_overload',
 'swelling_of_stomach',
 'swelled_lymph_nodes',
 'blurred_and_distorted_vision',
 'throat_irritation',
 'redness_of_eyes',
 'runny_nose',
 'congestion',
 'weakness_in_limbs',
 'fast_heart_rate',
 'pain_in_anal_region',
 'bloody_stool',
 'irritation_in_anus',
 'dizziness',
 'cramps',
 'bruising',
 'obesity',
 'swollen_legs',
 'swollen_blood_vessels',
 'puffy_face_and_eyes',
 'brittle_nails',
 'swollen_extremeties',
 'excessive_

In [ ]:
for i in columns :
    # drop low importance features
    train_df.drop(i, axis=1, inplace=True)
    test_df.drop(i, axis=1, inplace=True)
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   itching                      4920 non-null   int64 
 1   skin_rash                    4920 non-null   int64 
 2   shivering                    4920 non-null   int64 
 3   chills                       4920 non-null   int64 
 4   vomiting                     4920 non-null   int64 
 5   fatigue                      4920 non-null   int64 
 6   cough                        4920 non-null   int64 
 7   high_fever                   4920 non-null   int64 
 8   headache                     4920 non-null   int64 
 9   yellowish_skin               4920 non-null   int64 
 10  nausea                       4920 non-null   int64 
 11  loss_of_appetite             4920 non-null   int64 
 12  abdominal_pain               4920 non-null   int64 
 13  diarrhoea                    4920

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   itching                      4920 non-null   int64 
 1   skin_rash                    4920 non-null   int64 
 2   shivering                    4920 non-null   int64 
 3   chills                       4920 non-null   int64 
 4   vomiting                     4920 non-null   int64 
 5   fatigue                      4920 non-null   int64 
 6   cough                        4920 non-null   int64 
 7   high_fever                   4920 non-null   int64 
 8   headache                     4920 non-null   int64 
 9   yellowish_skin               4920 non-null   int64 
 10  nausea                       4920 non-null   int64 
 11  loss_of_appetite             4920 non-null   int64 
 12  abdominal_pain               4920 non-null   int64 
 13  diarrhoea                    4920

In [ ]:
# split dataset into attributes and labels
X_train = train_df.iloc[:, :-1].values # the training attributes
y_train = train_df.iloc[:, 33].values # the training labels
X_test = test_df.iloc[:, :-1].values # the testing attributes
y_test = test_df.iloc[:, 33].values # the testing labels

# using DT based on information gain
classifierDT = DecisionTreeClassifier(splitter='best', criterion='entropy', min_samples_leaf=2)
classifierDT.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2)

In [ ]:
# for DT model
y_predDT = classifierDT.predict(X_test)

# using confusion matrix
print(confusion_matrix(y_test, y_predDT))
print(classification_report(y_test, y_predDT))

# using accuracy performance metric
print("Train Accuracy: ", accuracy_score(y_train, classifierDT.predict(X_train)))
print("Test Accuracy: ", accuracy_score(y_test, y_predDT))

[[120   0   0 ...   0   0   0]
 [  0 120   0 ...   0   0   0]
 [  0   6 114 ...   0   0   0]
 ...
 [  0   6   0 ... 114   0   0]
 [  0   6   0 ...   0 114   0]
 [  0   0   0 ...   0   0 120]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00       120
                                   AIDS       0.80      1.00      0.89       120
                                   Acne       0.83      0.95      0.88       120
                    Alcoholic hepatitis       1.00      0.95      0.97       120
                                Allergy       1.00      1.00      1.00       120
                              Arthritis       1.00      0.95      0.97       120
                       Bronchial Asthma       1.00      1.00      1.00       120
                   Cervical spondylosis       1.00      1.00      1.00       120
                            Chicken pox       1.00      1.00      1.00       1

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
classifierRF = RandomForestClassifier(criterion='entropy', min_samples_leaf=2)
classifierRF.fit(X_train, Y_train)
y_predRF = classifierRF.predict(X_test)

print(confusion_matrix(Y_test, y_predRF))
print(classification_report(Y_test, y_predRF))

# using accuracy performance metric
print("Train Accuracy: ", accuracy_score(Y_train, classifierRF.predict(X_train)))
print("Test Accuracy: ", accuracy_score(Y_test, y_predRF))

[[120   0   0 ...   0   0   0]
 [  0 114   0 ...   0   0   0]
 [  0   0 114 ...   0   0   0]
 ...
 [  0   0   0 ... 114   0   0]
 [  0   0   0 ...   0 114   0]
 [  0   0   0 ...   0   0 120]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00       120
                                   AIDS       1.00      0.95      0.97       120
                                   Acne       0.83      0.95      0.88       120
                    Alcoholic hepatitis       1.00      0.95      0.97       120
                                Allergy       1.00      1.00      1.00       120
                              Arthritis       0.80      1.00      0.89       120
                       Bronchial Asthma       1.00      1.00      1.00       120
                   Cervical spondylosis       1.00      1.00      1.00       120
                            Chicken pox       1.00      1.00      1.00       1

In [ ]:
# new data on 33 attributes
newdata = [[0, 1,0,0,  0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 
            0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0]]
#PREDICTION WITH DT
# compute probabilities of assigning to each of the classes of prognosis
probaDT = classifierDT.predict_proba(newdata)
probaDT.round(4) # round probabilities to four decimal places, if applicable

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# make prediction of target class label
predDT = classifierDT.predict(newdata)
predDT

array(['Hepatitis E'], dtype=object)

In [ ]:
# new data on 33 attributes
newdata = [[0, 0,0,  0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 
            0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,0]]
#PREDICTION WITH RF
# compute probabilities of assigning to each of the classes of prognosis
probaDT = classifierRF.predict_proba(newdata)
probaDT.round(4) # round probabilities to four decimal places, if applicable
# make prediction of target class label
predDT = classifierRF.predict(newdata)
predDT

array(['Hypoglycemia'], dtype=object)